
const params=new URLSearchParams(location.search);
const BOOT={round:params.get('round')||'',admin:params.get('admin')==='1'};
const $=id=>document.getElementById(id);
let state=null,category='全部',cart=[],chosen=null,password='',pending=null;
const storageKey='drink-order:'+BOOT.round;
const money=n=>'$'+Number(n).toLocaleString('zh-TW');
const escapeHtml=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function hide(id,on=true){$(id).classList.toggle('hidden',on)}
function message(text,error=false){hide(error?'notice':'error');const id=error?'error':'notice';$(id).textContent=text;hide(id,false)}
function clearMessage(){hide('error');hide('notice')}
function api(fn,...args){return window.OrderingAPI.call(fn,...args)}
function saveDraft(){try{localStorage.setItem(storageKey,JSON.stringify({cart,name:$('name').value,pending}))}catch(e){}}
function loadDraft(){try{const d=JSON.parse(localStorage.getItem(storageKey)||'null');if(d){cart=Array.isArray(d.cart)?d.cart:[];$('name').value=d.name||'';pending=d.pending||null}}catch(e){}}
function options(id,values,preferred){$(id).replaceChildren(...values.map(v=>{const el=document.createElement('option');el.value=typeof v==='string'?v:v.value;el.textContent=typeof v==='string'?v:v.label;return el}));if(values.some(v=>(typeof v==='string'?v:v.value)===preferred))$(id).value=preferred}
function activeRound(){return state&&state.round.status==='open'&&(!state.round.deadline||Date.now()<Date.parse(state.round.deadline))}
function dateText(s){return s?new Date(s).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'未設定截止時間'}
function renderTabs(){const cats=['全部',...new Set(state.menu.map(i=>i.category))];$('tabs').replaceChildren(...cats.map(c=>{const b=document.createElement('button');b.className='chip'+(category===c?' active':'');b.textContent=c;b.onclick=()=>{category=c;renderTabs();renderMenu()};return b}))}
function renderMenu(){const query=$('search').value.trim();const items=state.menu.filter(i=>(category==='全部'||category===i.category)&&i.name.includes(query));$('menu').replaceChildren(...items.map(i=>{const b=document.createElement('button');b.className='drink';b.disabled=!activeRound()||!!pending;b.innerHTML='<div><span class="category">'+escapeHtml(i.category)+'</span><strong>'+escapeHtml(i.name)+'</strong><div class="price">'+Object.entries(i.prices).map(([s,p])=>escapeHtml(s)+' '+money(p)).join('　')+'</div></div><span class="plus" aria-hidden="true">＋</span>';b.onclick=()=>openDrink(i);return b}));if(!items.length)$('menu').textContent='找不到符合的餐點。'}
function openDrink(item){chosen=item;$('drinkName').textContent=item.name;$('drinkCategory').textContent=item.category;$('drinkRule').textContent=[item.sugarRule,item.iceRule,item.freePearl?'珍珠可免費加購':''].filter(Boolean).join(' · ');options('size',Object.entries(item.prices).map(([s,p])=>({value:s,label:s+'　'+money(p)})),'L');options('sugar',item.sugars,'微糖');options('ice',item.ices,'微冰');$('sugar').closest('.field').hidden=item.sugars.length===1&&item.sugars[0]==='不適用';$('ice').closest('.field').hidden=item.ices.length===1&&item.ices[0]==='不適用';$('quantity').value='1';$('note').value='';$('toppings').replaceChildren(...(item.extraOptions||state.toppings).filter(t=>item.toppingIds.includes(t.id)).map(t=>{const l=document.createElement('label');l.className='choice';const c=document.createElement('input');c.type='checkbox';c.value=t.id;c.onchange=updateLinePrice;l.append(c,document.createTextNode(t.name+(item.freePearl&&t.id==='pearl'?' 免費':' +'+money(item.addonPrices[t.id]))));return l}));if(!$('toppings').children.length)$('toppings').textContent='此餐點不提供加料';updateLinePrice();$('drinkDialog').showModal()}
function selectedToppings(){return Array.from($('toppings').querySelectorAll('input:checked')).map(c=>c.value)}
function unitPrice(item,size,toppings){return item.prices[size]+toppings.reduce((n,id)=>{const t=(item.extraOptions||state.toppings).find(t=>t.id===id);if(!t)throw Error('加料資料已更新');return n+(id==='pearl'&&item.freePearl?0:item.addonPrices[t.id])},0)}
function updateLinePrice(){if(chosen)$('linePrice').textContent=money(unitPrice(chosen,$('size').value,selectedToppings())*(Number($('quantity').value)||1))}
function renderCart(){const blocked=!!pending;$('name').disabled=blocked;$('cart').replaceChildren(...cart.map((line,index)=>{const el=document.createElement('div');el.className='cart-line';const item=state.menu.find(i=>i.id===line.id);el.innerHTML='<div class="line-head"><span>'+escapeHtml(item?item.name:'品項已更新')+' '+escapeHtml(line.size)+' ×'+line.quantity+'</span><span>'+money(line.subtotal)+'</span></div><div class="line-meta">'+escapeHtml([line.sugar,line.ice,line.toppingText].filter(x=>x!=='不適用').join('／'))+'</div>'+(line.note?'<div class="line-meta">'+escapeHtml(line.note)+'</div>':'');const b=document.createElement('button');b.className='remove';b.textContent='移除';b.disabled=blocked;b.onclick=()=>{cart.splice(index,1);saveDraft();renderCart()};el.append(b);return el}));if(!cart.length)$('cart').innerHTML='<div class="cart-empty">先選一份喜歡的餐點吧。<br>加到這裡，再一起送出。</div>';$('cups').textContent='共 '+cart.reduce((n,l)=>n+l.quantity,0)+' 份';$('total').textContent=money(cart.reduce((n,l)=>n+l.subtotal,0));$('submit').textContent=pending?'重試送出，確認前次結果':'送出訂單';$('submit').disabled=!cart.length||(!activeRound()&&!pending);hide('pendingNote',!pending);renderMenu()}
async function init(){try{if(!BOOT.admin&&!BOOT.round){showHome();return}if(BOOT.admin){hide('loading');hide('login',false);$('status').textContent='主揪管理';return}state=await api('getPublicState',BOOT.round);$('storeTitle').textContent=state.round.store;$('roundInfo').textContent=state.round.title+' · '+dateText(state.round.deadline);$('status').textContent=activeRound()?'開放點餐':'已收單';loadDraft();if(!pending){cart=cart.filter(l=>state.menu.some(i=>i.id===l.id&&i.prices[l.size]!==undefined&&i.sugars.includes(l.sugar)&&i.ices.includes(l.ice)&&l.toppings.every(t=>i.toppingIds.includes(t))));cart.forEach(l=>{const item=state.menu.find(i=>i.id===l.id);l.subtotal=unitPrice(item,l.size,l.toppings)*l.quantity});saveDraft()}renderTabs();renderCart();hide('loading');hide('orderView',false);if(!activeRound())message('這一團已收單，無法新增訂單。')}catch(e){hide('loading');$('status').textContent='無法開啟點餐';message(e.message,true);hide('errorHome',false)}}
function showHome(){clearMessage();['loading','orderView','receipt','login','admin','errorHome'].forEach(id=>hide(id));hide('home',false);$('status').textContent='歡迎';password='';$('password').value=''}
$('openAdmin').onclick=()=>{clearMessage();hide('home');hide('login',false);$('status').textContent='主揪管理';$('password').focus()};
$('loginHome').onclick=showHome;$('errorHome').onclick=showHome;
$('search').oninput=renderMenu;$('name').oninput=saveDraft;$('closeDialog').onclick=()=>$('drinkDialog').close();['size','quantity'].forEach(id=>$(id).oninput=updateLinePrice);
$('drinkForm').onsubmit=e=>{e.preventDefault();const quantity=Number($('quantity').value);if(!Number.isInteger(quantity)||quantity<1||quantity>50)return;const toppings=selectedToppings();cart.push({id:chosen.id,size:$('size').value,sugar:$('sugar').value,ice:$('ice').value,quantity,toppings,note:$('note').value.trim(),subtotal:unitPrice(chosen,$('size').value,toppings)*quantity,toppingText:toppings.map(id=>{const t=(chosen.extraOptions||state.toppings).find(t=>t.id===id);return t.name+(id==='pearl'&&chosen.freePearl?'（免費）':'')}).join('＋')||'無'});saveDraft();renderCart();$('drinkDialog').close();message('已加入 '+chosen.name+'，選好後按「送出訂單」。')};
function requestId(){if(window.crypto&&crypto.randomUUID)return crypto.randomUUID();if(!window.crypto||!crypto.getRandomValues)throw Error('瀏覽器版本過舊，請更新後再點餐。');const a=new Uint8Array(20);crypto.getRandomValues(a);return Array.from(a,x=>x.toString(16).padStart(2,'0')).join('')}
$('submit').onclick=async()=>{clearMessage();if(!pending){const name=$('name').value.trim();if(!name){$('name').focus();message('請先填寫姓名。',true);return}if(cart.reduce((n,l)=>n+l.quantity,0)>50){message('每次送單最多50份。',true);return}if(cart.length>30){message('每次送單最多30項餐點。',true);return}pending={roundId:BOOT.round,requestId:requestId(),name,items:cart.map(({id,size,sugar,ice,quantity,toppings,note})=>({id,size,sugar,ice,quantity,toppings,note})),expectedTotal:cart.reduce((n,l)=>n+l.subtotal,0)};saveDraft();renderCart()}$('submit').disabled=true;$('submit').textContent='正在送出…';try{const receipt=await api('submitOrder',pending);pending=null;if(receipt.rejected){saveDraft();renderCart();message(receipt.message+' 此筆沒有新增，請修正後再送出。',true);return}cart=[];saveDraft();renderReceipt(receipt)}catch(e){message(e.message+' 若是網路或系統暫時錯誤，請按「重試送出」；系統不會重複記錄同一筆。',true);renderCart()}};
function renderReceipt(r){hide('orderView');hide('receipt',false);$('status').textContent='送單成功';$('receipt').innerHTML='<div class="success-icon">✓</div><div class="eyebrow">ORDER RECEIVED</div><h1>已送出，'+escapeHtml(r.name)+'</h1><p class="muted">主揪已收到你的訂單。共 '+r.cups+' 份，應付 '+money(r.total)+'。</p>'+r.lines.map(l=>'<div class="cart-line"><div class="line-head"><span>'+escapeHtml(l.name)+' '+escapeHtml(l.size)+' ×'+l.quantity+'</span><span>'+money(l.subtotal)+'</span></div><div class="line-meta">'+escapeHtml([l.sugar,l.ice,l.toppings,l.note].filter(x=>x&&x!=='不適用').join('／'))+'</div></div>').join('')+'<p class="help">訂單編號：'+escapeHtml(r.orderId)+'</p>';const b=document.createElement('button');b.className='secondary wide';b.style.marginTop='20px';b.textContent='再點一筆新訂單';b.onclick=()=>{hide('receipt');hide('orderView',false);renderCart();$('status').textContent=activeRound()?'開放點餐':'已收單'};$('receipt').append(b)}
$('loginForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;clearMessage();try{password=$('password').value;const data=await api('adminAction',password,'list',{});$('password').value='';hide('login');hide('admin',false);renderAdmin(data)}catch(e){password='';message(e.message,true)}finally{b.disabled=false}};
function renderAdmin(data){options('storeSelect',data.stores.map(s=>({value:s.name,label:s.name+'（'+s.count+'款）'})),$('storeSelect').value);$('folderLink').href=data.folderUrl;$('rounds').replaceChildren(...data.rounds.map(r=>{const el=document.createElement('article');el.className='round-card';const closed=r.status!=='open'||(r.deadline&&Date.now()>=Date.parse(r.deadline));el.innerHTML='<span class="badge">'+(closed?'已收單':'開放點餐')+'</span><h3 style="margin-top:8px">'+escapeHtml(r.title)+'</h3><div class="status-note">'+escapeHtml(dateText(r.deadline))+'</div><div class="metrics"><span><strong>'+r.people+'</strong> 人</span><span><strong>'+r.cups+'</strong> 份</span><span>總金額 <strong>'+money(r.total)+'</strong></span></div>';const actions=document.createElement('div');actions.className='round-actions';const copy=document.createElement('button');copy.className='secondary';copy.textContent='複製點餐連結';copy.onclick=async()=>{try{await navigator.clipboard.writeText(r.url);message('已複製，將連結傳給同事即可點餐。')}catch(e){window.prompt('請複製這個點餐連結',r.url)}};const a=document.createElement('a');a.href=r.sheetUrl;a.target='_blank';a.rel='noopener';a.textContent='開啟訂單試算表';actions.append(copy,a);if(r.status==='open'){const close=document.createElement('button');close.className='secondary';close.textContent='收單';close.onclick=async()=>{if(!confirm('確定收單？收單後同事不能再新增訂單。'))return;close.disabled=true;try{renderAdmin(await api('adminAction',password,'close',{roundId:r.id}));message('已收單，試算表也已更新。')}catch(e){message(e.message,true);close.disabled=false}};actions.append(close)}const rebuild=document.createElement('button');rebuild.className='secondary';rebuild.textContent='重整彙總';rebuild.onclick=async()=>{rebuild.disabled=true;try{renderAdmin(await api('adminAction',password,'rebuild',{roundId:r.id}));message('彙總已更新。')}catch(e){message(e.message,true);rebuild.disabled=false}};actions.append(rebuild);el.append(actions);return el}));if(!data.rounds.length)$('rounds').innerHTML='<div class="panel muted">還沒有團購。選擇店家，按「開團並產生連結」即可開始。</div>'}
$('createForm').onsubmit=async e=>{e.preventDefault();$('create').disabled=true;clearMessage();try{const deadline=$('deadline').value;const result=await api('adminAction',password,'create',{store:$('storeSelect').value,deadline:deadline?deadline+':00+08:00':''});renderAdmin(result.state);message('已開團：'+result.round.title+'。請按「複製點餐連結」分享。')}catch(e){message(e.message,true)}finally{$('create').disabled=false}};
$('refresh').onclick=async()=>{$('refresh').disabled=true;try{renderAdmin(await api('adminAction',password,'list',{}));message('訂單已更新。')}catch(e){message(e.message,true)}finally{$('refresh').disabled=false}};
init();
